---
- name: Ansible Vault Example
  hosts: all
  become: true
  vars_files:
    - vault.yml
    
  tasks:
    - name : ensure git is installed
      yum:
        name: git
        state: present

    - name: clone a git repository
      git:
        repo: "https://gowniraghu:{{ password | urlencode }}@github.com/gowniraghu/git_course.git"
        dest: /opts/git_course/