---
- name: create a user
  hosts: all
  become: true
  vars:
    username: john
  vars_files:
    - user.yml  

  tasks:
  - name: create a user using variable
    user:
      name: "{{ username }}"
      state: present

  - name: create a user using variable file 
    user:
      name: "{{ user }}"
      state: present